/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.*;
import java.sql.*;
import ulti.ConnectDB;

public class LoginFrame extends javax.swing.JFrame {

    public LoginFrame() {
        initComponents();
        setLocationRelativeTo(null); // Căn giữa màn hình

        // Thiết lập giá trị cho combo box
        cbLoaitaikhoan.setModel(new DefaultComboBoxModel<>(new String[]{"Khách Hàng", "Nhân Viên", "Chủ Cửa Hàng"}));

        // Gắn sự kiện cho các nút
        btnDangNhap.addActionListener(e -> dangNhap());
        btnDangKy.addActionListener(e -> dangKy());
        btnThoat.addActionListener(e -> System.exit(0));
    }

    private void dangNhap() {
        String tk = txtTenTaiKhoan.getText().trim();
        String mk = new String(txtMatKhau.getPassword()).trim();
        String loai = cbLoaitaikhoan.getSelectedItem().toString();

        try (Connection con = ConnectDB.getConnection()) {
            PreparedStatement stmt;
            if (loai.equals("Khách Hàng")) {
                stmt = con.prepareStatement("SELECT * FROM KhachHang WHERE maKhachHang=? AND ngaySinh=?");
                stmt.setLong(1, Long.parseLong(tk));
                stmt.setDate(2, Date.valueOf(mk));
            } else {
                stmt = con.prepareStatement("SELECT * FROM TaiKhoanNV WHERE maTaiKhoan=? AND password=? AND permission=?");
                stmt.setLong(1, Long.parseLong(tk));
                stmt.setLong(2, Long.parseLong(mk));
                stmt.setString(3, loai.equals("Nhân Viên") ? "staff" : "admin");
            }

            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
                if (loai.equals("Khách Hàng")) {
                    new trangchu().setVisible(true);
                } else if (loai.equals("Nhân Viên")) {
                    new QuanLySanPham().setVisible(true);
                } else {
                    new MainPage().setVisible(true);
                }
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Sai tài khoản hoặc mật khẩu");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        }
    }

    private void dangKy() {
        String tk = txtTenTaiKhoan.getText().trim();
        String mk = new String(txtMatKhau.getPassword()).trim();
        String loai = cbLoaitaikhoan.getSelectedItem().toString();

        try (Connection con = ConnectDB.getConnection()) {
            PreparedStatement stmt;
            if (loai.equals("Khách Hàng")) {
                stmt = con.prepareStatement(
                        "INSERT INTO KhachHang (maKhachHang, tenKhachHang, diaChi, SDT, ngaySinh, gioiTinh) VALUES (?, 'Mặc định', 'Mặc định', 0, ?, 1)");
                stmt.setLong(1, Long.parseLong(tk));
                stmt.setDate(2, Date.valueOf(mk));
            } else {
                stmt = con.prepareStatement(
                        "INSERT INTO TaiKhoanNV (maTaiKhoan, Email, password, namSinh, SDT, permission) VALUES (?, '', ?, CURRENT_DATE, 0, ?)");
                stmt.setLong(1, Long.parseLong(tk));
                stmt.setString(2, mk);
                stmt.setString(3, loai.equals("Nhân Viên") ? "staff" : "admin");
            }

            int rows = stmt.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Đăng ký thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Đăng ký thất bại!");
            }
        } catch (SQLIntegrityConstraintViolationException ex) {
            JOptionPane.showMessageDialog(this, "Tài khoản đã tồn tại");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbLoaitaikhoan = new javax.swing.JComboBox<>();
        txtTenTaiKhoan = new javax.swing.JTextField();
        btnThoat = new javax.swing.JButton();
        btnDangKy = new javax.swing.JButton();
        btnDangNhap = new javax.swing.JButton();
        txtTenTaiKhoan1 = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ten TK");

        jLabel2.setText("Mat Khau");

        jLabel3.setText("Loại Tai Khoan");

        cbLoaitaikhoan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân Viên", "Khách Hàng", "Chủ Cửa Hàng" }));

        txtTenTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenTaiKhoanActionPerformed(evt);
            }
        });

        btnThoat.setText("thoat");

        btnDangKy.setText("Dang Ky");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });

        btnDangNhap.setText("Dang Nhap");

        txtTenTaiKhoan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenTaiKhoan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbLoaitaikhoan, 0, 315, Short.MAX_VALUE)
                            .addComponent(txtTenTaiKhoan)
                            .addComponent(txtTenTaiKhoan1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(btnDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(btnDangNhap)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenTaiKhoan1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLoaitaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void txtTenTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenTaiKhoanActionPerformed

    private void txtTenTaiKhoan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenTaiKhoan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenTaiKhoan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    // ... (Giữ nguyên phần cấu hình Look and Feel ở đây, nếu có) ...

    // Chỉ cần một lệnh gọi này là đủ
    java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cbLoaitaikhoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtTenTaiKhoan;
    private javax.swing.JTextField txtTenTaiKhoan1;
    // End of variables declaration//GEN-END:variables
}
