/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import entity.*;
import dao.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author meoba
 */
public class ProdmgmtJP extends javax.swing.JPanel {

    ProductDAO PDAO = new ProductDAO();
    LoaiDAO LDAO = new LoaiDAO();

    public ProdmgmtJP() {
        initComponents();
        JLabel lbl = new JLabel("Đây là giao diện quản lý nhân viên");
        add(lbl);
        this.listItems();
        this.listTypes();
    }

    public void listItems() {
        DefaultTableModel model1 = (DefaultTableModel) prodList.getModel();
        model1.setRowCount(0);
        for (productEntity product : PDAO.getAllProducts()) {
            Object[] data = {product.getID(), product.getName(), product.getType(), product.getDesc(), product.getPrice()};
            model1.addRow(data);
        }
        prodList.setModel(model1);
    }

    public void listTypes() {
        DefaultComboBoxModel model1 = (DefaultComboBoxModel) typeList.getModel();
        model1.removeAllElements();
        for (LoaiEntity1 type : LDAO.getAll()) {
            Object data = String.valueOf(type.getTen());
            model1.addElement(data);
        }
        typeList.setModel(model1);
    }

    public void showItems(int index) {
        IDBox.setText(String.valueOf(prodList.getValueAt(index, 0)));
        NameBox.setText(String.valueOf(prodList.getValueAt(index, 1)));
        typeList.setSelectedItem(String.valueOf(prodList.getValueAt(index, 2)));
        DescBox.setText(String.valueOf(prodList.getValueAt(index, 3)));
        PriceBox.setText(String.valueOf(prodList.getValueAt(index, 4)));
    }

    public void updateItem() {
        long ID = Long.parseLong(IDBox.getText());
        LoaiEntity1 type = LDAO.getByName(typeList.getSelectedItem().toString());
        long typeID = type.getMaLoai();
        String desc = DescBox.getText();
        int price = Integer.parseInt(PriceBox.getText());
        String name = NameBox.getText();
        productEntity product = new productEntity(ID, typeID, name, desc, price);

        int choice = JOptionPane.showConfirmDialog(null, "Bạn có muốn cập nhật cho " + name + " không?", "Cập nhật sản phẩm", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            PDAO.updateProduct(product);
            JOptionPane.showMessageDialog(null, "Cập nhật thành công.");
        }
    }

    public void addItem() {
        int option = JOptionPane.showConfirmDialog(null, "Thêm " + NameBox.getText() + "?", "Thêm nội thất", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            LoaiEntity1 type = LDAO.getByName(typeList.getSelectedItem().toString());
            long typeID = type.getMaLoai();
            String desc = DescBox.getText();
            int price = Integer.parseInt(PriceBox.getText());
            String name = NameBox.getText();
            productEntity product = new productEntity(typeID, name, desc, price);
            PDAO.addProduct(product);
            JOptionPane.showMessageDialog(null, "Thêm nội thất thành công.");
        }
        listItems();
        
    }

    public void delItem(long ID) {

        int choice = JOptionPane.showConfirmDialog(null, "Bạn có muốn xoá không?", "Xoá nội thất", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            PDAO.deleteProduct(ID);
            JOptionPane.showMessageDialog(null, "Nội thất xoá thành công.");
        } else {
            JOptionPane.showMessageDialog(null, "Nội thất đã không xoá.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IDBox = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        prodList = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NameBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DescBox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PriceBox = new javax.swing.JTextField();
        fixBtn = new javax.swing.JButton();
        typeList = new javax.swing.JComboBox<>();

        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mã nội thất");

        IDBox.setEditable(false);
        IDBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        addBtn.setBackground(new java.awt.Color(0, 204, 0));
        addBtn.setText("Thêm");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        delButton.setBackground(new java.awt.Color(204, 0, 0));
        delButton.setText("Xoá");
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });

        prodList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Nội Thất", "Tên Nội Thất", "Tên Loại", "Mô Tả", "Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        prodList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prodListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(prodList);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Quản Lý Nội Thất");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tên Nội Thất");

        NameBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tên Loại");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Mô Tả");

        DescBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Giá");

        PriceBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        fixBtn.setText("Sửa");
        fixBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(IDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(NameBox, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                        .addComponent(typeList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(delButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fixBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(PriceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(DescBox, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(IDBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(typeList, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(DescBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PriceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        addItem();
    }//GEN-LAST:event_addBtnActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        int index = prodList.getSelectedRow();
        if (index != -1) {
            long ID = Long.parseLong(prodList.getValueAt(index, 0).toString());
            delItem(ID);
        }
        else {
            JOptionPane.showMessageDialog(null, "Xin hãy chọn nội thất ở bảng bên dưới.");
        }
    }//GEN-LAST:event_delButtonActionPerformed

    private void fixBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixBtnActionPerformed
        updateItem();
    }//GEN-LAST:event_fixBtnActionPerformed

    private void prodListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodListMouseClicked
        int index = prodList.getSelectedRow();
        showItems(index);
    }//GEN-LAST:event_prodListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DescBox;
    private javax.swing.JTextField IDBox;
    private javax.swing.JTextField NameBox;
    private javax.swing.JTextField PriceBox;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton delButton;
    private javax.swing.JButton fixBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable prodList;
    private javax.swing.JComboBox<String> typeList;
    // End of variables declaration//GEN-END:variables
}
