/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class trangchu extends javax.swing.JFrame {

    /**
     * Creates new form trangchu
     */
    public trangchu() {
        initComponents();
        pnlMain.setLayout(new BorderLayout());
        

    }
    private void showPanel(JPanel panel) {
        pnlMain.removeAll();
        pnlMain.add(panel, BorderLayout.CENTER);
        pnlMain.revalidate();
        pnlMain.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tblquanlynhanvien = new javax.swing.JButton();
        btnqanlyKH = new javax.swing.JButton();
        btlquanlysanpham = new javax.swing.JButton();
        tblchitiensanpham = new javax.swing.JButton();
        tblloai = new javax.swing.JButton();
        tblVouchers = new javax.swing.JButton();
        tblkhohang = new javax.swing.JButton();
        tblthoat = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        pnlMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabel1.setText("Tên");

        tblquanlynhanvien.setText("Quản ly nhân viên");
        tblquanlynhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblquanlynhanvienMouseClicked(evt);
            }
        });

        btnqanlyKH.setText("Quản lý khách hàng");
        btnqanlyKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnqanlyKHMouseClicked(evt);
            }
        });

        btlquanlysanpham.setText("Quản ly sản phẩm");
        btlquanlysanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btlquanlysanphamMouseClicked(evt);
            }
        });

        tblchitiensanpham.setText("Chi tiết sản phẩm");
        tblchitiensanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblchitiensanphamMouseClicked(evt);
            }
        });

        tblloai.setText("Loại");
        tblloai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblloaiMouseClicked(evt);
            }
        });

        tblVouchers.setText("Vouchers");
        tblVouchers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVouchersMouseClicked(evt);
            }
        });

        tblkhohang.setText("Kho hàng");
        tblkhohang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblkhohangMouseClicked(evt);
            }
        });

        tblthoat.setText("Thoát");
        tblthoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblthoatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tblthoat)
                    .addComponent(tblkhohang)
                    .addComponent(tblVouchers)
                    .addComponent(tblloai)
                    .addComponent(tblchitiensanpham)
                    .addComponent(btlquanlysanpham)
                    .addComponent(btnqanlyKH)
                    .addComponent(tblquanlynhanvien)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tblquanlynhanvien)
                .addGap(18, 18, 18)
                .addComponent(btnqanlyKH)
                .addGap(18, 18, 18)
                .addComponent(btlquanlysanpham)
                .addGap(18, 18, 18)
                .addComponent(tblchitiensanpham)
                .addGap(18, 18, 18)
                .addComponent(tblloai)
                .addGap(18, 18, 18)
                .addComponent(tblVouchers)
                .addGap(18, 18, 18)
                .addComponent(tblkhohang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(tblthoat))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblquanlynhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblquanlynhanvienMouseClicked
            showPanel(new TaiKhoanNhanVien());
    }//GEN-LAST:event_tblquanlynhanvienMouseClicked

    private void btnqanlyKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnqanlyKHMouseClicked
 showPanel(new Khachhang());    }//GEN-LAST:event_btnqanlyKHMouseClicked

    private void btlquanlysanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlquanlysanphamMouseClicked
      showPanel(new QuanLySanPham()); 
    }//GEN-LAST:event_btlquanlysanphamMouseClicked

    private void tblchitiensanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblchitiensanphamMouseClicked
showPanel(new ChiTietSanPham());     }//GEN-LAST:event_tblchitiensanphamMouseClicked

    private void tblloaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblloaiMouseClicked
        showPanel(new Loai());
    }//GEN-LAST:event_tblloaiMouseClicked

    private void tblVouchersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVouchersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblVouchersMouseClicked

    private void tblkhohangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkhohangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblkhohangMouseClicked

    private void tblthoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblthoatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblthoatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trangchu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlquanlysanpham;
    private javax.swing.JButton btnqanlyKH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JButton tblVouchers;
    private javax.swing.JButton tblchitiensanpham;
    private javax.swing.JButton tblkhohang;
    private javax.swing.JButton tblloai;
    private javax.swing.JButton tblquanlynhanvien;
    private javax.swing.JButton tblthoat;
    // End of variables declaration//GEN-END:variables
}
